### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by sjaakie72** [GuntharDeNiro/Gunthy#64] opened 2017-12-23 00:32 UTC
Loading config...
INVALID LICENSE FOR BITTREX!!! Please contact Gunthar!
Loading config...
INVALID LICENSE FOR BITTREX!!! Please contact Gunthar!
Loading config...
INVALID LICENSE FOR BITTREX!!! Please contact Gunthar!
Loading config...
INVALID LICENSE FOR BITTREX!!! Please contact Gunthar!
Loading config...

**Comment by dotpim** [comment] 2017-12-23 00:43
This is a software issue tracker, this is not meant for customer support. The problem you describe is not a bug, I am closing this issue.

Please seek help in the Wiki or Telegram group - or ask your Reseller for help.

Relevant Link: https://github.com/GuntharDeNiro/BTCT/wiki/Windows-installation

**Closed by dotpim** 2017-12-23 00:43 UTC
